version: '3.8'
services:
  misis-inquiry:
    container_name: misis-inquiry
    image: misisbot
    stop_signal: SIGINT
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
